# fly.toml for Production Deployment
app = "vibegrapher-api"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    [services.http_checks.headers]

# Production scaling - never scale to 0
[metrics]
  port = 9091
  path = "/metrics"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[processes]
  app = "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

# Mount persistent volume for media/projects
[mounts]
  source = "vibegrapher_data"
  destination = "/app/media"

# Auto-scaling configuration for production
[services.auto_stop_machines]
  enable = false

[services.auto_start_machines]
  enable = true
  min_machines_running = 1