"""Add comprehensive streaming fields to ConversationMessage

Revision ID: 7fc5bef6e21d
Revises: aaf3c676709f
Create Date: 2025-08-27 03:00:44.388079

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fc5bef6e21d"
down_revision: str | None = "aaf3c676709f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns one by one for SQLite compatibility
    op.add_column("conversation_messages", sa.Column("input", sa.JSON(), nullable=True))
    op.add_column(
        "conversation_messages", sa.Column("new_items", sa.JSON(), nullable=True)
    )
    op.add_column(
        "conversation_messages", sa.Column("final_output", sa.Text(), nullable=True)
    )
    op.add_column(
        "conversation_messages",
        sa.Column("final_output_typed", sa.JSON(), nullable=True),
    )
    op.add_column(
        "conversation_messages", sa.Column("last_agent", sa.String(), nullable=True)
    )
    op.add_column(
        "conversation_messages", sa.Column("tool_outputs", sa.JSON(), nullable=True)
    )
    op.add_column(
        "conversation_messages", sa.Column("handoffs", sa.JSON(), nullable=True)
    )
    op.add_column(
        "conversation_messages",
        sa.Column("usage_input_tokens", sa.Integer(), nullable=True),
    )
    op.add_column(
        "conversation_messages",
        sa.Column("usage_output_tokens", sa.Integer(), nullable=True),
    )
    op.add_column(
        "conversation_messages",
        sa.Column("usage_total_tokens", sa.Integer(), nullable=True),
    )
    op.add_column(
        "conversation_messages",
        sa.Column("usage_cached_tokens", sa.Integer(), nullable=True),
    )
    op.add_column(
        "conversation_messages",
        sa.Column("usage_reasoning_tokens", sa.Integer(), nullable=True),
    )
    op.add_column(
        "conversation_messages",
        sa.Column("stream_event_type", sa.String(), nullable=True),
    )
    op.add_column(
        "conversation_messages",
        sa.Column("stream_sequence", sa.Integer(), nullable=True),
    )
    op.add_column(
        "conversation_messages", sa.Column("event_data", sa.JSON(), nullable=True)
    )
    # Note: We can't alter column or drop columns in SQLite without recreating the table
    # For now, just leave content as is and agent_type remains
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support dropping columns easily, would need to recreate table
    # For simplicity, we'll leave this as a no-op
    pass
    # ### end Alembic commands ###
