"""Initial migration with all models

Revision ID: aaf3c676709f
Revises: 
Create Date: 2025-08-26 00:55:26.361552

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaf3c676709f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("repository_path", sa.String(), nullable=True),
        sa.Column("current_code", sa.Text(), nullable=True),
        sa.Column("current_commit", sa.String(), nullable=True),
        sa.Column("current_branch", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        sa.UniqueConstraint("slug", name="uq_project_slug"),
    )
    op.create_table(
        "vibecode_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("openai_session_key", sa.String(), nullable=False),
        sa.Column("conversations_db_path", sa.String(), nullable=False),
        sa.Column("session_type", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("openai_session_key"),
    )
    op.create_table(
        "diffs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("base_commit", sa.String(), nullable=False),
        sa.Column("target_branch", sa.String(), nullable=False),
        sa.Column("diff_content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("test_results", sa.Text(), nullable=True),
        sa.Column("tests_run_at", sa.DateTime(), nullable=True),
        sa.Column("vibecoder_prompt", sa.Text(), nullable=False),
        sa.Column("evaluator_reasoning", sa.Text(), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=False),
        sa.Column("human_feedback", sa.Text(), nullable=True),
        sa.Column("committed_sha", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["vibecode_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("openai_response", sa.JSON(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("diff_id", sa.String(), nullable=True),
        sa.Column("last_response_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diff_id"],
            ["diffs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["vibecode_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_messages")
    op.drop_table("diffs")
    op.drop_table("vibecode_sessions")
    op.drop_table("projects")
    # ### end Alembic commands ###
