name: Cleanup Preview Environment

on:
  pull_request:
    types: [closed]
    paths:
      - 'backend/**'

jobs:
  cleanup:
    name: Destroy Preview App
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Generate App Name
        id: app_name
        run: |
          APP_NAME="vibegrapher-api-pr-${{ github.event.pull_request.number }}"
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
      
      - name: Check if Preview App Exists
        id: check_app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if flyctl apps list | grep -q "${{ steps.app_name.outputs.app_name }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Destroy Preview App
        if: steps.check_app.outputs.exists == 'true'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "🧹 Destroying preview app: ${{ steps.app_name.outputs.app_name }}"
          flyctl apps destroy ${{ steps.app_name.outputs.app_name }} --yes
      
      - name: Comment on PR
        if: steps.check_app.outputs.exists == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const appName = '${{ steps.app_name.outputs.app_name }}';
            const prNumber = context.issue.number;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## 🧹 Preview Environment Cleaned Up
              
              The preview environment **${appName}** has been destroyed.
              
              Thank you for your contribution!`
            });